### ISSUE TITLE
Расширение допустимых типов пропса onClick компонента Button

### ISSUE THREAD

**Issue by alex-kurkov** [yandex-praktikum/react-developer-burger-ui-components#22]
Привет!

Предлагаю поправить типизацию компонента Button, а именно - добавить пропсу onClick типизацию аргумента
    `onClick?: (() => void) |  ((e: SyntheticEvent) => void);`

Сейчас в TS компоненте нельзя удобно и напрямую передавать в onClick кнопки колбек с обработкой события сабмита формы с отменой дефолтного поведения, приходится плодить доп обертки

**Comment by boredcity** [comment]
наверно, нужно закрыть этот issue?

**Comment by yandex-praktikum** [comment]
PR влит, в ближайшее время соберем все "горящие" реквесты в один релиз и опубликуем в NPM. Вернусь в Issue с информацией после релиза

**Comment by zlocate** [comment]
Проблема устранена в PR #23, обновите пожалуйста библиотеку до последней версии
