### ISSUE TITLE
Устаревшие peer dependencies

### ISSUE THREAD

**Issue by boredcity** [yandex-praktikum/react-developer-burger-ui-components#33]
Привет 👋 

Из-за устаревших peer dependencies [тут](https://github.com/yandex-praktikum/react-developer-burger-ui-components/blob/4b427b99dcf61b821a2b49a4495ca41b25f4bc14/package.json#L78) ловится эта ошибка на 17-м реакте и npm выше 6-й версии при `npm i @ya.praktikum/react-developer-burger-ui-components`:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: react-burger@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from @ya.praktikum/react-developer-burger-ui-components@1.12.0
npm ERR! node_modules/@ya.praktikum/react-developer-burger-ui-components
npm ERR!   @ya.praktikum/react-developer-burger-ui-components@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/merelj/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/merelj/.npm/_logs/2021-10-07T16_22_14_840Z-debug.log
```
временно рекомендую лечить это с помощью `--legacy-peer-deps`, но было бы круто поправить 🙏

**Comment by boredcity** [comment]
и, возможно, стоит добавить инструкцию для пользователей с не самой свежей PowerShell отсюда: https://stackoverflow.com/questions/37834613/npm-scoped-packages-and-powershell/51671566 👀

**Comment by abi83** [comment]
Plus one for the issue!

**Comment by boredcity** [comment]
тоже, видимо, можно закрыть?

upd: а, нет, не влит еще пр

**Comment by yandex-praktikum** [comment]
Благодарим за обращение. В течение ближайших двух недель планируем опубликовать новую версию, совместимую в React 18.
Вернусь в Issue с информацией об обновлении :)

**Comment by zlocate** [comment]
Проблема устранена в последнем релизе
