### ISSUE TITLE
Поправить типы пропсов компонента Button под 18 React

### ISSUE THREAD

**Issue by ZheniaEU** [yandex-praktikum/react-developer-burger-ui-components#39]
![image](https://user-images.githubusercontent.com/85547727/185752394-7257a0f3-930b-439c-94d0-caf78247d146.png)

примерное решение проблемы добавить   **children?: ReactNode**
```ts
export declare const Button: React.FC<{
    type?: 'secondary' | 'primary';
    size?: 'small' | 'medium' | 'large';
    onClick?: (() => void) | ((e: SyntheticEvent) => void);
    disabled?: boolean;
    name?: string;
    htmlType?: 'button' | 'submit' | 'reset';
    
    children?: ReactNode;
}>;
```

**Comment by yandex-praktikum** [comment]
Благодарим за обращение. В течение ближайших двух недель планируем опубликовать новую версию, совместимую в React 18.
Вернусь в Issue с информацией об обновлении :)

**Comment by zlocate** [comment]
Проблема исправлена, спасибо за репорт
